# Generated by Django 4.0.3 on 2019-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220402_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
