# Generated by Django 4.0.3 on 2022-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220402_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
