# Generated by Django 4.0.3 on 2022-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220402_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
